name: compile-and-release
on: [workflow_dispatch]
jobs:
  compile-assets-and-push-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
      - run: npm install
      - uses: montudor/action-zip@v1
        with:
          args: zip -qq -r dist.zip ./
      - name: Deploy to Lambda
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ca-central-1
          function_name: ${{ secrets.AWS_LAMBDA_FUNCTION_NAME }}
          zip_file: dist.zip
          runtime: nodejs18.x